# Generated on Fri 20 Dec 14:32:22 CET 2019.
# CHANGES TO THIS FILE WILL BE LOST.

CONF_ARGS='--hdf5-libs=hdf5_serial --hdf5-incdirs=/usr/include/hdf5/serial'
SH='/bin/dash'
SH_NAME='dash'
AR='ar -rucs'
OBJ_SUFFIX='.o'
EXE_SUFFIX=''
LIB_PREFIX='lib'
LIB_SUFFIX='.a'
DLL_PREFIX='lib'
DLL_SUFFIX='.so'
CXX='g++'
CXX_NAME='gcc'
CXX_VERSION='90201'
CXX_STD_FLAGS='-O -Wall -fstrict-aliasing -m64 -msse2 -mtune=native'
CXX_DBG_FLAGS='-g'
CXX_PRF_FLAGS='-pg'
CXX_DLL_FLAGS='-fPIC'
CXX_LNK_FLAGS='-rdynamic'
CXX_BLD_FLAG=''
CXX_OPT_FLAGS1='-O1 -DNDEBUG -funroll-loops'
CXX_OPT_FLAGS2='-O2 -DNDEBUG -funroll-loops'
CXX_OPT_FLAGS3='-O3 -DNDEBUG -funroll-loops -ftree-vectorize'
CXX_OPT_LEVEL='3'
SYS_NAME='linux'
SYS_IS_POSIX='1'
SYS_IS_UNIX98='1'
SYS_ARCH='x86_64'
SYS_BITS='64'
SYS_LIBS=' pthread m'
SYS_LIBDIRS=''
SYS_INCDIRS=''
INDEX_TYPE='int'
USE_THREADS='1'
USE_CCACHE=''

